### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Joanwal** [Kicer86/photobroom#154]
For me it would be nice if these things have appeared:
- option that pictures in album can be shown without frames and data
- autocompletition names, places etc. during writing informations about pictures
- scaling pictures to see them clearly

**Comment by Kicer86** [comment]
- Photos Collection should have defined location for photos and all photos should be moved there
- adopt "add photos" to new feature above (moving photos and inteligent scan for photos location)

**Comment by Kicer86** [comment]
All ideas were addressed
