### ISSUE TITLE
It is hard do locate face in faces dialog on 4K

### ISSUE THREAD

**Issue by Kicer86** [Kicer86/photobroom#361]
Number are too small to see them on photo. 
Use different colors or similar solution to make it easier to find proper person.

**Comment by perpetumstudio** [comment]
I would reccomend to highlight selected person and rectangle around his face at the same time. So user, can jump to the next person on the list (with arrow down/up) and assiociated rectangle, reflects selected person with highlighted rectangle around faces. That would be nice to associate colours with recognised faces. But it should also work for color-blind people.

**Comment by Kicer86** [comment]
Restore rectangles around found faces

**Comment by Kicer86** [comment]
I believe it is fine now
