### ISSUE TITLE
Unsupported files icon

### ISSUE THREAD

**Issue by perpetumstudio** [Kicer86/photobroom#392]
When it happened: After creating new Collection, when content of selected folder is loaded. Some of the loaded files, like movies are displayed but not supported.
And it looks like that:
![image](https://user-images.githubusercontent.com/3620842/103477886-4e25e580-4dc3-11eb-8689-1a0f189aa44f.png)
The red cross looks a bit to much alarming for me, so I would recommend one of the solutions:
- do not load (and not to display them) unsupported files at all
- mark unsupported files with the question mark icon instead of the red cross, and keep red cross reserved for corrupted files

**Comment by Kicer86** [comment]
X for video files appears when ffmpeg is not set. This need is not presented to the user :/
Related to #267

**Comment by Kicer86** [comment]
possibly fixed by #400

**Comment by Kicer86** [comment]
fix for #402 should be final solution

**Comment by Kicer86** [comment]
considering it fixed
